ZI/ManuelaKajkara/Controllers/Kazne_WCFController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL.EF;
using ManuelaKajkara.BLLProviders;

namespace ManuelaKajkara.Controllers
{
    public class Kazne_WCFController : Controller
    {
        private RPPP10 db = new RPPP10();

        // GET: /Kazne_WCF/
        public ActionResult Index(string Sort, string Pretraga)
        {
            ViewBag.ImeSort = String.IsNullOrEmpty(Sort) ? "Ime_asc" : "";
            ViewBag.PrezimeSort = Sort == "Prezime" ? "Prezime_desc" : "Prezime";
            ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

            var kazna = WCF.DajSveKazne();
            List<Kazna> kazne = new List<Kazna>();

            foreach (ServiceReference1.Kazna i in kazna)
            {
                Kazna j = new Kazna();
                j.Osoba = new FizickaOsoba();
                j.IDOsobe = i.IDOsobe;
                j.IDKazne = i.IDKazne;
                j.IDPresude = i.IDPresude;
                j.Presuda = i.Presuda;
                j.Vrsta = i.Vrsta;
                j.Iznos = i.Iznos;
                j.Naziv = i.Naziv;
                j.Osoba.ImePrezime = i.Osoba.ImePrezime;
                j.Osoba.Prezime = i.Osoba.Prezime;
                j.Osoba.Ime = i.Osoba.Ime;
                j.Opis = i.Opis;
                j.Vrsta=i.Vrsta;
                kazne.Add(j);
            }

            WCF.Close();
            var vrste = new VrKaBLL().FetchAll();
            List<VrKa> vrk = new List<VrKa>();
            foreach (var item in vrste) vrk.Add(item);
            ViewBag.VrstaKazne = vrk;

            if (!String.IsNullOrEmpty(Pretraga))
            {
                kazne = kazne.Where(x => x.Osoba.ImePrezime.ToLower().Contains(Pretraga.ToLower())).ToList();
            }

            switch (Sort)
            {
                case "Ime_asc":
                    kazne = kazne.OrderBy(x => x.Osoba.Ime).ToList();
                    break;
                case "Prezime":
                    kazne = kazne.OrderBy(x => x.Osoba.Prezime).ToList();
                    break;
                case "Prezime_desc":
                    kazne= kazne.OrderByDescending(x => x.Osoba.Prezime).ToList();
                    break;
                default:
                    kazne = kazne.OrderByDescending(x => x.Osoba.Ime).ToList();
                    break;
            }
            foreach (Kazna item in kazne)
            {
                item.Naziv = new KaznaBLL().vrstaKazne((int)item.Vrsta).ToString();
                item.Presuda = new KaznaBLL().vrstaPresude((int)item.IDPresude).ToString();
            }

            return View(kazne);
        }

        // GET: /Kazne_WCF/Create
        public ActionResult Create()
        {
            return RedirectToAction("Kazni","Kazne");
        }

        // POST: /Kazne_WCF/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
       /* [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDOsobe,Ime,Prezime,ImeOca,Datum,JMBG,Poslodavac,Odvjetnik,Sudac,OIB,Adresa,Mjesto")] FizOsoba fizickaosoba)
        {
            if (ModelState.IsValid)
            {
                ServiceReference1.FizOsoba osoba = new ServiceReference1.FizOsoba();

                osoba.Ime = fizickaosoba.Ime;
                osoba.Prezime = fizickaosoba.Prezime;
                osoba.ImeOca = fizickaosoba.ImeOca;
                osoba.Datum = fizickaosoba.Datum;
                osoba.JMBG = fizickaosoba.JMBG;
                osoba.Poslodavac = fizickaosoba.Poslodavac;
                osoba.Odvjetnik = fizickaosoba.Odvjetnik;
                osoba.Sudac = fizickaosoba.Sudac;
                osoba.Adresa = fizickaosoba.Adresa;
                osoba.OIB = fizickaosoba.OIB;
                osoba.Mjesto = fizickaosoba.Mjesto;

                ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

                WCF.UnesiFizickuOsobu(osoba);

                WCF.Close();

                return RedirectToAction("Index");
            }

            ViewBag.IDOsobe = new SelectList(db.Osoba, "IDOsobe", "OIB", fizickaosoba.IDOsobe);
            ViewBag.Poslodavac = new SelectList(db.PravnaOsoba, "IDOsobe", "Naziv", fizickaosoba.Poslodavac);
            return View(fizickaosoba);
        }
        */
        // GET: /Kazne_WCF/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ServiceReference1.Kazna kazna = new ServiceReference1.Kazna();

            ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

            kazna = WCF.DajKaznu((int)id);

            if (kazna == null)
            {
                return HttpNotFound();
            }

            Kazna kaz = new Kazna();
            kaz.Osoba = new FizickaOsoba();
            kaz.IDOsobe = kazna.IDOsobe;
            kaz.IDKazne = kazna.IDKazne;
            kaz.IDPresude = kazna.IDPresude;
            kaz.Iznos = kazna.Iznos;
            kaz.Osoba.ImePrezime = kazna.Osoba.ImePrezime;
            kaz.Osoba.Prezime = kazna.Osoba.Prezime;
            kaz.Osoba.Ime = kazna.Osoba.Ime;
            kaz.Naziv = kazna.Naziv;
            kaz.Opis = kazna.Opis;
            kaz.Presuda = kazna.Presuda;
            kaz.Vrsta = kazna.Vrsta;

            WCF.Close();
            ViewBag.IDOsobe = new SelectList(db.Osoba, "IDOsobe", "OIB", kazna.IDOsobe);
            ViewBag.IDPresude = new SelectList(db.Presuda, "IDStavke", "IDStavke", kazna.IDPresude);
            ViewBag.Vrsta = new SelectList(db.VrstaKazne, "SifraVrste", "NazivVrste", kazna.Vrsta);

            return View(kaz);
        }

        // POST: /Kazne_WCF/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "IDOsobe,IDKazne,IDPresude,Iznos,Naziv,Opis,Presuda,Vrsta")]*/ Kazna kazna)
        {

                ServiceReference1.Kazna kaz = new ServiceReference1.Kazna();
                kaz.Osoba = new ServiceReference1.FizickaOsoba();
                kaz.IDOsobe = kazna.IDOsobe;
                kaz.IDKazne = kazna.IDKazne;
                kaz.IDPresude = kazna.IDPresude;
                kaz.Iznos = kazna.Iznos;
                kaz.Opis = kazna.Opis;
                kaz.Vrsta = kazna.Vrsta;

                ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

                WCF.PromijeniKaznu(kaz);

                WCF.Close();

                return RedirectToAction("Index");

        }

        // GET: /Kazne_WCF/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ServiceReference1.Kazna kazna = new ServiceReference1.Kazna();

            ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

            kazna = WCF.DajKaznu((int)id);

            if (kazna == null)
            {
                return HttpNotFound();
            }

            Kazna kaz = new Kazna();
            kaz.Osoba = new FizickaOsoba();
            kaz.IDOsobe = kazna.IDOsobe;
            kaz.IDKazne = kazna.IDKazne;
            kaz.IDPresude = kazna.IDPresude;
            kaz.Iznos = kazna.Iznos;
            kaz.Naziv = kazna.Naziv;
            kaz.Opis = kazna.Opis;
            kaz.Osoba.ImePrezime = kazna.Osoba.ImePrezime;
            kaz.Osoba.Prezime = kazna.Osoba.Prezime;
            kaz.Osoba.Ime = kazna.Osoba.Ime;
            kaz.Presuda = kazna.Presuda;
            kaz.Vrsta = kazna.Vrsta;

            WCF.Close();           
                
            kaz.Naziv = new KaznaBLL().vrstaKazne((int)kaz.Vrsta).ToString();
            kaz.Presuda = new KaznaBLL().vrstaPresude((int)kaz.IDPresude).ToString();


            return View(kaz);
        }

        // POST: /Kazne_WCF/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

            WCF.ObrisiKaznu(id);

            WCF.Close();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/ManuelaKajkara/Views/Kazne_WCF/Create.cshtml
@model DAL.EF.Kazna

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kazna</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.IDKazne, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDKazne)
                @Html.ValidationMessageFor(model => model.IDKazne)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDPresude, "IDPresude", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDPresude", String.Empty)
                @Html.ValidationMessageFor(model => model.IDPresude)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDOsobe, "IDOsobe", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDOsobe", String.Empty)
                @Html.ValidationMessageFor(model => model.IDOsobe)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vrsta, "Vrsta", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Vrsta", String.Empty)
                @Html.ValidationMessageFor(model => model.Vrsta)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Iznos, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Iznos)
                @Html.ValidationMessageFor(model => model.Iznos)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis)
                @Html.ValidationMessageFor(model => model.Opis)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ZI/ManuelaKajkara/Views/Kazne_WCF/Delete.cshtml
@model ManuelaKajkara.Kazna

@{
    ViewBag.Title = "Brisanje";
}

<h2>Brisanje</h2>

<h3>Sigurni ste?</h3>
<div>
    <h4>Kazna</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Iznos
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Iznos)
        </dd>

        <dt>
            Opis
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            Osoba
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Osoba.ImePrezime)
        </dd>

        <dt>
            Vrsta presude
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Presuda)
        </dd>

        <dt>
            Vrsta kazne
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Nazad", "Index")
        </div>
    }
</div>

ZI/ManuelaKajkara/Views/Kazne_WCF/Details.cshtml
@model Kazna

@{
    ViewBag.Title = "Detalji";
}

<h2>Detalji</h2>

<div>
    <h4>Kazna</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Iznos
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Iznos)
        </dd>

        <dt>
            Opis
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            Osoba
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Osoba.ImePrezime)
        </dd>

        <dt>
            Presuda
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Presuda)
        </dd>

        <dt>
            Vrsta kazne
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Uredi", "Edit", new { id = Model.IDKazne }) |
    @Html.ActionLink("Povratak", "Index")
</p>

ZI/ManuelaKajkara/Views/Kazne_WCF/Edit.cshtml
@model Kazna

@{
    ViewBag.Title = "Uredi";
}

<h2>Uredi</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kazna</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.IDKazne, "IDKazne")

        <div class="form-group" style="display:none;">
            @Html.LabelFor(model => model.IDPresude, "Presuda", new { @class = "control-label col-md-2" })
            <div class="col-md-10" >
                @Html.DropDownList("IDPresude")
            </div>
        </div>

        @Html.HiddenFor(model => model.IDOsobe, "IDOsobe")

        <div class="form-group">
            @Html.LabelFor(model => model.Vrsta, "Vrsta", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Vrsta", String.Empty)
                @Html.ValidationMessage("Vrsta", "Neispravan unos!")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Iznos, "Iznos", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Iznos)
                @Html.ValidationMessage("Iznos", "Neispravan unos!")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, "Opis", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis)
                @Html.ValidationMessage("Opis", "Opis je obaveezan!")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Odustani", "Index")
</div>

ZI/ManuelaKajkara/Views/Kazne_WCF/Index.cshtml
@model IEnumerable<Kazna>

@{
    ViewBag.Title = "Kazne (uz WCF)";
}

<h2>Kazne (uz WCF)</h2>

<p>
    @Html.ActionLink("Nova", "Create")
</p>
@using (Html.BeginForm("Index", "Kazne_WCF", FormMethod.Get))
    {
<p>
    Pretraga po prezimenu osobe: @Html.TextBox("Pretraga") <input type="submit" value="Pretraži" />
</p>
    }

@Html.ActionLink("Prikaži sve", "Index")
<table class="table">
    <tr>
        <th>
            Iznos
        </th>
        <th>
            Opis
        </th>
        <th>
            Osoba (@Html.ActionLink("Ime", "Index", new { Sort = ViewBag.ImeSort }) i @Html.ActionLink("prezime", "Index", new { Sort = ViewBag.PrezimeSort }))
        </th>
        <th>
            Presuda
        </th>
        <th>
            Vrsta kazne
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Iznos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Osoba.ImePrezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Presuda)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.ActionLink("Uredi", "Edit", new { id=item.IDKazne }) <br>
            @Html.ActionLink("Obriši", "Delete", new { id=item.IDKazne })
        </td>
    </tr>
}

</table>