ZI/ManuelaKajkara/Controllers/FizOsobeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL.EF;

namespace ManuelaKajkara.Controllers
{
    public class FizOsobeController : Controller
    {
        private RPPP10 db = new RPPP10();

        // GET: /FizOsobe/
        public ActionResult Index(string Sort, string Pretraga)
        {
            ViewBag.ImeSort = String.IsNullOrEmpty(Sort) ? "Ime_desc" : "";
            ViewBag.PrezimeSort = Sort == "Prezime" ? "Prezime_desc" : "Prezime";

            ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

            var fizickaosoba = WCF.DajSveFizickeOsobe();

            List<FizOsoba> Osobe = new List<FizOsoba>();

            foreach (ServiceReference1.FizOsoba i in fizickaosoba) {
                FizOsoba j = new FizOsoba();
                j.IDOsobe = i.IDOsobe;
                j.Ime = i.Ime;
                j.Prezime = i.Prezime;
                j.ImeOca = i.ImeOca;
                j.Datum = i.Datum;
                j.JMBG = i.JMBG;
                j.Poslodavac = i.Poslodavac;
                j.Odvjetnik = i.Odvjetnik;
                j.Sudac = i.Sudac;
                j.Adresa = i.Adresa;
                j.OIB = i.OIB;
                j.Mjesto = i.Mjesto;
                Osobe.Add(j);
            }

            WCF.Close();

            if (!String.IsNullOrEmpty(Pretraga))
            {
                Osobe = Osobe.Where(x => x.Ime.Contains(Pretraga)).ToList();
            }

            switch (Sort)
            {
                case "Ime_desc":
                    Osobe = Osobe.OrderByDescending(x => x.Ime).ToList();
                    break;
                case "Prezime":
                    Osobe = Osobe.OrderBy(x => x.Prezime).ToList();
                    break;
                case "Prezime_desc":
                    Osobe = Osobe.OrderByDescending(x => x.Prezime).ToList();
                    break;
                default:
                    Osobe = Osobe.OrderBy(x => x.Ime).ToList();
                    break;
            }

            return View(Osobe);
        }

        // GET: /FizOsobe/Create
        public ActionResult Create()
        {
            ViewBag.IDOsobe = new SelectList(db.Osoba, "IDOsobe", "OIB");
            ViewBag.Poslodavac = new SelectList(db.PravnaOsoba, "IDOsobe", "Naziv");
            return View();
        }

        // POST: /FizOsobe/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDOsobe,Ime,Prezime,ImeOca,Datum,JMBG,Poslodavac,Odvjetnik,Sudac,OIB,Adresa,Mjesto")] FizOsoba fizickaosoba)
        {
            if (ModelState.IsValid)
            {
                ServiceReference1.FizOsoba osoba = new ServiceReference1.FizOsoba();

                osoba.Ime = fizickaosoba.Ime;
                osoba.Prezime = fizickaosoba.Prezime;
                osoba.ImeOca = fizickaosoba.ImeOca;
                osoba.Datum = fizickaosoba.Datum;
                osoba.JMBG = fizickaosoba.JMBG;
                osoba.Poslodavac = fizickaosoba.Poslodavac;
                osoba.Odvjetnik = fizickaosoba.Odvjetnik;
                osoba.Sudac = fizickaosoba.Sudac;
                osoba.Adresa = fizickaosoba.Adresa;
                osoba.OIB = fizickaosoba.OIB;
                osoba.Mjesto = fizickaosoba.Mjesto;

                ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

                WCF.UnesiFizickuOsobu(osoba);

                WCF.Close();

                return RedirectToAction("Index");
            }

            ViewBag.IDOsobe = new SelectList(db.Osoba, "IDOsobe", "OIB", fizickaosoba.IDOsobe);
            ViewBag.Poslodavac = new SelectList(db.PravnaOsoba, "IDOsobe", "Naziv", fizickaosoba.Poslodavac);
            return View(fizickaosoba);
        }

        // GET: /FizOsobe/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ServiceReference1.FizOsoba osoba = new ServiceReference1.FizOsoba();

            ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

            osoba = WCF.DajFizickuOsobu((int)id);

            if (osoba == null)
            {
                return HttpNotFound();
            }

            FizOsoba fizickaosoba = new FizOsoba();

            fizickaosoba.IDOsobe = osoba.IDOsobe;
            fizickaosoba.Ime = osoba.Ime;
            fizickaosoba.Prezime = osoba.Prezime;
            fizickaosoba.ImeOca = osoba.ImeOca;
            fizickaosoba.Datum = osoba.Datum;
            fizickaosoba.JMBG = osoba.JMBG;
            fizickaosoba.Poslodavac = osoba.Poslodavac;
            fizickaosoba.Odvjetnik = osoba.Odvjetnik;
            fizickaosoba.Sudac = osoba.Sudac;
            fizickaosoba.Adresa = osoba.Adresa;
            fizickaosoba.OIB = osoba.OIB;
            fizickaosoba.Mjesto = osoba.Mjesto;

            WCF.Close();

            ViewBag.IDOsobe = new SelectList(db.Osoba, "IDOsobe", "OIB", fizickaosoba.IDOsobe);
            ViewBag.Poslodavac = new SelectList(db.PravnaOsoba, "IDOsobe", "Naziv", fizickaosoba.Poslodavac);

            return View(fizickaosoba);
        }

        // POST: /FizOsobe/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDOsobe,Ime,Prezime,ImeOca,Datum,JMBG,Poslodavac,Odvjetnik,Sudac,OIB,Adresa,Mjesto")] FizOsoba fizickaosoba)
        {
            if (ModelState.IsValid)
            {
                ServiceReference1.FizOsoba osoba = new ServiceReference1.FizOsoba();

                osoba.IDOsobe = fizickaosoba.IDOsobe;
                osoba.Ime = fizickaosoba.Ime;
                osoba.Prezime = fizickaosoba.Prezime;
                osoba.ImeOca = fizickaosoba.ImeOca;
                osoba.Datum = fizickaosoba.Datum;
                osoba.JMBG = fizickaosoba.JMBG;
                osoba.Poslodavac = fizickaosoba.Poslodavac;
                osoba.Odvjetnik = fizickaosoba.Odvjetnik;
                osoba.Sudac = fizickaosoba.Sudac;
                osoba.Adresa = fizickaosoba.Adresa;
                osoba.OIB = fizickaosoba.OIB;
                osoba.Mjesto = fizickaosoba.Mjesto;

                ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

                WCF.PromijeniFizickuOsobu(osoba);

                WCF.Close();

                return RedirectToAction("Index");
            }
            ViewBag.IDOsobe = new SelectList(db.Osoba, "IDOsobe", "OIB", fizickaosoba.IDOsobe);
            ViewBag.Poslodavac = new SelectList(db.PravnaOsoba, "IDOsobe", "Naziv", fizickaosoba.Poslodavac);
            return View(fizickaosoba);
        }

        // GET: /FizOsobe/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ServiceReference1.FizOsoba osoba = new ServiceReference1.FizOsoba();

            ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

            osoba = WCF.DajFizickuOsobu((int)id);

            if (osoba == null)
            {
                return HttpNotFound();
            }

            FizOsoba fizickaosoba = new FizOsoba();

            fizickaosoba.IDOsobe = osoba.IDOsobe;
            fizickaosoba.Ime = osoba.Ime;
            fizickaosoba.Prezime = osoba.Prezime;
            fizickaosoba.ImeOca = osoba.ImeOca;
            fizickaosoba.Datum = osoba.Datum;
            fizickaosoba.JMBG = osoba.JMBG;
            fizickaosoba.Poslodavac = osoba.Poslodavac;
            fizickaosoba.Odvjetnik = osoba.Odvjetnik;
            fizickaosoba.Sudac = osoba.Sudac;
            fizickaosoba.Adresa = osoba.Adresa;
            fizickaosoba.OIB = osoba.OIB;
            fizickaosoba.Mjesto = osoba.Mjesto;

            WCF.Close();

            return View(fizickaosoba);
        }

        // POST: /FizOsobe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceReference1.FirmaServisClient WCF = new ServiceReference1.FirmaServisClient();

            WCF.ObrisiFizickuOsobu(id);

            WCF.Close();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/ManuelaKajkara/Views/FizOsobe/Create.cshtml
@model FizOsoba

@{
    ViewBag.Title = "Dodavanje fizičke osobe";
}

<h2>Dodavanje fizičke osobe</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime)
                @Html.ValidationMessageFor(model => model.Ime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime)
                @Html.ValidationMessageFor(model => model.Prezime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImeOca, "Ime oca", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImeOca)
                @Html.ValidationMessageFor(model => model.ImeOca)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, "Datum dd/mm/yyyy", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum)
                @Html.ValidationMessageFor(model => model.Datum)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JMBG, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JMBG)
                @Html.ValidationMessageFor(model => model.JMBG)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poslodavac, "Poslodavac", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Poslodavac", String.Empty)
                @Html.ValidationMessageFor(model => model.Poslodavac)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Odvjetnik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Odvjetnik)
                @Html.ValidationMessageFor(model => model.Odvjetnik)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sudac, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sudac)
                @Html.ValidationMessageFor(model => model.Sudac)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OIB, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OIB)
                @Html.ValidationMessageFor(model => model.OIB)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa)
                @Html.ValidationMessageFor(model => model.Adresa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mjesto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Mjesto, new SelectList(new MjestoBLL().DajSvaImena()))
                @Html.ValidationMessageFor(model => model.Mjesto)
                @Html.ActionLink("Uredi mjesta", "../Mjesto/Index")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Unesi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "Index")
</div>

ZI/ManuelaKajkara/Views/FizOsobe/Delete.cshtml
@model FizOsoba

@{
    ViewBag.Title = "Brisanje fizičke osobe";
}

<h2>Brisanje fizičke osobe</h2>

<h3>Jeste li sigurni da želite obrisati ovu fizičku osobu?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ime
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            Prezime
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            Ime oca
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImeOca)
        </dd>

        <dt>
            Datum rođenja
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Datum)
        </dd>

        <dt>
            JMBG
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JMBG)
        </dd>

        <dt>
            Odvjetnik
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Odvjetnik)
        </dd>

        <dt>
            Sudac
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sudac)
        </dd>

        <dt>
            OIB
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OIB)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Povratak", "Index")
        </div>
    }
</div>

ZI/ManuelaKajkara/Views/FizOsobe/Edit.cshtml
@model FizOsoba

@{
    ViewBag.Title = "Uredi fizičku osobu";
}

<h2>Uredi fizičku osobu</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.IDOsobe)

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime)
                @Html.ValidationMessageFor(model => model.Ime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime)
                @Html.ValidationMessageFor(model => model.Prezime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImeOca, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImeOca)
                @Html.ValidationMessageFor(model => model.ImeOca)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, "Datum dd/mm/yyyy", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum)
                @Html.ValidationMessageFor(model => model.Datum)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JMBG, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JMBG)
                @Html.ValidationMessageFor(model => model.JMBG)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poslodavac, "Poslodavac", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Poslodavac", new PravnaOsobaBLL().DajJednuID(Model.Poslodavac).Naziv)
                @Html.ValidationMessageFor(model => model.Poslodavac)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Odvjetnik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Odvjetnik)
                @Html.ValidationMessageFor(model => model.Odvjetnik)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sudac, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sudac)
                @Html.ValidationMessageFor(model => model.Sudac)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OIB, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OIB)
                @Html.ValidationMessageFor(model => model.OIB)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa)
                @Html.ValidationMessageFor(model => model.Adresa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mjesto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Mjesto, new SelectList(new MjestoBLL().DajSvaImena(), Model.Mjesto))
                @Html.ValidationMessageFor(model => model.Mjesto)
                @Html.ActionLink("Uredi mjesta", "../Mjesto/Index")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "Index")
</div>

ZI/ManuelaKajkara/Views/FizOsobe/Index.cshtml
@model IEnumerable<FizOsoba>

@{
    ViewBag.Title = "Fizičke osobe";
}

<h2>Fizičke osobe</h2>

<p>
    @Html.ActionLink("Dodaj novu", "Create")
    @using (Html.BeginForm("Index", "FizOsobe", FormMethod.Get))
    {
    <p>
        Naziv: @Html.TextBox("Pretraga") <input type="submit" value="Pretraži" />
    </p>
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Ime", "Index", new { Sort = ViewBag.ImeSort })
        </th>
        <th>
            @Html.ActionLink("Prezime", "Index", new { Sort = ViewBag.PrezimeSort })
        </th>
        <th>
            Ime oca
        </th>
        <th>
            Datum rođenja
        </th>
        <th>
            JMBG
        </th>
        <th>
            Odvjetnik
        </th>
        <th>
            Sudac
        </th>
        <th>
            OIB
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImeOca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Datum.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JMBG)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Odvjetnik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sudac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OIB)
        </td>
        <td>
            @Html.ActionLink("Uredi", "Edit", new { id=item.IDOsobe }) |
            @Html.ActionLink("Obriši", "Delete", new { id=item.IDOsobe })
        </td>
    </tr>
}

</table>