ZI/ManuelaKajkara/Controllers/ProcesINIController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL.EF;
using ManuelaKajkara.Models;
using ManuelaKajkara.BLLProviders;

namespace ManuelaKajkara.Controllers
{
    public class ProcesINIController : Controller
    {
        private RPPP10 db = new RPPP10();

        // GET: /ProcesINI/
        public ActionResult Index()
        {
            var proces = db.Proces.Include(p => p.VrstaOznake).Include(p => p.Sud1);
            return View(proces.ToList());
        }

        public ActionResult Search()
        {
            var vrste = new VrstaOznakeBLL().DajSveOznake();
            List<VrstaOznake> vro = new List<VrstaOznake>();
            foreach (var item in vrste) vro.Add(item);
            ViewBag.VrstaOznake = vro;

            var sudi = new SudBLL().FetchAll();
            List<Sud> sudovi = new List<Sud>();
            foreach (var item in sudi) sudovi.Add(item);
            ViewBag.Sudovi = sudovi;

            Proces_trazi model = new Proces_trazi
            {
                Naziv = "",
                Sud = -777,
                Vrsta = "Odaberi"
            };
            ViewBag.Nadjeni = "ne";
            return View(model);
        }

        [HttpPost, ActionName("Search")]
        public ActionResult Rezultati(Proces_trazi trazi)
        {

            ProNad_lista nadeno = new ProNad_lista();
            nadeno.Procesi = new List<ProcesPD>();

            List<ProcesPD> pro = new List<ProcesPD>();
            if (trazi.Naziv == null) trazi.Naziv = "";
            if (trazi.Vrsta == null) trazi.Vrsta = "Odaberi";
            if (trazi.Sud == 0) trazi.Sud = -777;
            if (trazi.Sud == -777)
            {
                if (trazi.Vrsta == "Odaberi")
                {
                    pro = new ProcesBLL().TraziNazSudVrs(trazi.Naziv);
                }
                else
                {
                    pro = new ProcesBLL().TraziNazSudVrs(trazi.Naziv, -777, trazi.Vrsta);
                }
            }
            else
            {

                pro = new ProcesBLL().TraziNazSudVrs(trazi.Naziv, trazi.Sud, trazi.Vrsta);
            }

            if (pro != null)
            {
                nadeno.Procesi = pro;
                ViewBag.Nadjeni = "da";
            }
            else {
                nadeno.Procesi = null;
                ViewBag.Nadjeni = "ne";
            }

            return View("~/Views/ProcesINI/Rezultati.cshtml", nadeno);
        }

        // GET: /ProcesINI/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proces proces = db.Proces.Find(id);
            if (proces == null)
            {
                return HttpNotFound();
            }
            return View(proces);
        }

        // GET: /ProcesINI/Create
        public ActionResult Create()
        {
            ViewBag.Oznaka = new SelectList(db.VrstaOznake, "SifraOznake", "OpisOznake");
            ViewBag.Sud = new SelectList(db.Sud, "IDSuda", "Naziv");
            return View();
        }

        // POST: /ProcesINI/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="IDProcesa,Broj,Klasa,Oznaka,Naziv,Sud")] Proces proces)
        {
            if (ModelState.IsValid)
            {
                db.Proces.Add(proces);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Oznaka = new SelectList(db.VrstaOznake, "SifraOznake", "OpisOznake", proces.Oznaka);
            ViewBag.Sud = new SelectList(db.Sud, "IDSuda", "Naziv", proces.Sud);
            return View(proces);
        }

        // GET: /ProcesINI/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proces proces = db.Proces.Find(id);
            if (proces == null)
            {
                return HttpNotFound();
            }
            ViewBag.Oznaka = new SelectList(db.VrstaOznake, "SifraOznake", "OpisOznake", proces.Oznaka);
            ViewBag.Sud = new SelectList(db.Sud, "IDSuda", "Naziv", proces.Sud);
            return View(proces);
        }

        // POST: /ProcesINI/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="IDProcesa,Broj,Klasa,Oznaka,Naziv,Sud")] Proces proces)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proces).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Oznaka = new SelectList(db.VrstaOznake, "SifraOznake", "OpisOznake", proces.Oznaka);
            ViewBag.Sud = new SelectList(db.Sud, "IDSuda", "Naziv", proces.Sud);
            return View(proces);
        }

        // GET: /ProcesINI/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proces proces = db.Proces.Find(id);
            if (proces == null)
            {
                return HttpNotFound();
            }
            return View(proces);
        }

        // POST: /ProcesINI/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Proces proces = db.Proces.Find(id);
            db.Proces.Remove(proces);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/ManuelaKajkara/Views/ProcesINI/Create.cshtml
@model DAL.EF.Proces

@{
    ViewBag.Title = "Novi proces";
}

<h2>Novi proces</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proces</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.IDProcesa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDProcesa)
                @Html.ValidationMessageFor(model => model.IDProcesa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Broj,"Ur. broj", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Broj)
                @Html.ValidationMessageFor(model => model.Broj)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Klasa,"Klasa", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Klasa)
                @Html.ValidationMessageFor(model => model.Klasa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Oznaka, "Vrsta procesa", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Oznaka", String.Empty)
                @Html.ValidationMessageFor(model => model.Oznaka)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv,"Naziv", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv)
                @Html.ValidationMessageFor(model => model.Naziv)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sud, "Sud na kojem se vodi", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Sud", String.Empty)
                @Html.ValidationMessageFor(model => model.Sud)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Nazad", "Index")
</div>

ZI/ManuelaKajkara/Views/ProcesINI/Delete.cshtml
@model DAL.EF.Proces

@{
    ViewBag.Title = "Brisanje procesa";
}

<h2>Brisanje</h2>

<h3>Sigurno želite obrisati ovaj proces?</h3>
<div>
    <h4>Proces</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ur. broj
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Broj)
        </dd>

        <dt>
            Klasa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Klasa)
        </dd>

        <dt>
            Naziv
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            Vrsta procesa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrstaOznake.OpisOznake)
        </dd>

        <dt>
            Sud na kojem se vodi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sud1.Naziv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Nazad", "Index")
        </div>
    }
</div>

ZI/ManuelaKajkara/Views/ProcesINI/Details.cshtml
@model DAL.EF.Proces

@{
    ViewBag.Title = "Detalji";
}

<h2>Detalji procesa</h2>

<div>
    <h4>Proces</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Ur. broj
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Broj)
        </dd>

        <dt>
            Klasa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Klasa)
        </dd>

        <dt>
            Naziv
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            Vrsta procesa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrstaOznake.OpisOznake)
        </dd>

        <dt>
            Sud na kojem se vodi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sud1.Naziv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Uredi", "Edit", new { id = Model.IDProcesa }) |
    @Html.ActionLink("Nazad", "Index")
</p>

ZI/ManuelaKajkara/Views/ProcesINI/Edit.cshtml
@model DAL.EF.Proces

@{
    ViewBag.Title = "Uređivanje";
}

<h2>Uređivanje</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proces</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.IDProcesa)

        <div class="form-group">
            @Html.LabelFor(model => model.Broj, "Ur. broj", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Broj)
                @Html.ValidationMessageFor(model => model.Broj)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Klasa, "Klasa",new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Klasa)
                @Html.ValidationMessageFor(model => model.Klasa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Oznaka, "Vrsta procesa", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Oznaka", String.Empty)
                @Html.ValidationMessageFor(model => model.Oznaka)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, "Naziv",new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv)
                @Html.ValidationMessageFor(model => model.Naziv)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sud, "Sud na kojem se vodi", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Sud", String.Empty)
                @Html.ValidationMessageFor(model => model.Sud)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Nazad", "Index")
</div>

ZI/ManuelaKajkara/Views/ProcesINI/Index.cshtml
@model IEnumerable<DAL.EF.Proces>

@{
    ViewBag.Title = "Procesi";
}

<h2>Procesi</h2>

<p>
    @Html.ActionLink("Novi", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Ur. broj
        </th>
        <th>
            Klasa
        </th>
        <th>
            Naziv
        </th>
        <th>
            Vrsta procesa
        </th>
        <th>
            Sud na kojem se vodi
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Broj)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Klasa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VrstaOznake.OpisOznake)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sud1.Naziv)
        </td>
        <td>
            @Html.ActionLink("Uredi", "Edit", new { id=item.IDProcesa }) |
            @Html.ActionLink("Detalji", "Details", new { id=item.IDProcesa }) |
            @Html.ActionLink("Obriši", "Delete", new { id=item.IDProcesa })
        </td>
    </tr>
}

</table>

ZI/ManuelaKajkara/Views/ProcesINI/Rezultati.cshtml
@model ManuelaKajkara.Models.ProNad_lista
@{
    ViewBag.Title = "Rezultati";
}

<h2>Rezultati pretrage procesa</h2>

<table class="table">
    <tr>
        <th>
            Naziv
        </th>
        <th>
            Vrsta
        </th>
        <th>
            Sud
        </th>
        <th></th>
    </tr>

    @{
        if (ViewBag.Nadjeni != "da")
        {
            <tr>
                <td> --- </td>
                <td> --- </td>
                <td> --- </td>
            </tr>
        }
        else
        {
            foreach (var item in Model.Procesi)
            {
                <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Naziv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.VrstaProcesa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NazivSuda)
                        </td>
                        <td>
             @* PRIPAZI NA OVO ISPOD!!!!!!!!!!!!!!! *@
                            @Html.ActionLink("Uredi", "Edit", new { id = item.IDProcesa }) |
                            @Html.ActionLink("Detalji", "Details", new { id = item.IDProcesa }) |
                            @Html.ActionLink("Obriši", "Delete", new { id = item.IDProcesa })
                        </td>
                </tr>
            }
        }
    }
    @Html.ActionLink("Nova pretraga", "Search")
</table>

ZI/ManuelaKajkara/Views/ProcesINI/Search.cshtml
@model ManuelaKajkara.Models.Proces_trazi
@{
    ViewBag.Title = "Pretraga procesa";
}

<h2>Pretraga procesa</h2>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td colspan="2">@*@Html.ValidationSummary()*@</td>
        </tr>
        <tr>
            <td>Naziv procesa:</td>
            <td>@Html.EditorFor(m => m.Naziv,"")</td>
        </tr>
        <tr>
            <td>Vrsta:</td>
            <td>
                @Html.DropDownListFor(m => m.Vrsta, ((IEnumerable<VrstaOznake>)ViewBag.VrstaOznake).OrderBy(d => d.Opis).Select(d => new SelectListItem { Text = d.Opis, Value = d.SifraOznake }),"Odaberi","Odaberi")
            </td>
        </tr>
        <tr>
            <td>Sud:</td>
            <td>
                @Html.DropDownListFor(m => m.Sud, ((IEnumerable<Sud>)ViewBag.Sudovi).OrderBy(d => d.naziv).Select(d => new SelectListItem { Text = d.naziv, Value = d.ID.ToString() }),"Odaberi",-777)
            </td>
        </tr>
    </table>
    <h5><input type="submit" value="Pretraži" /></h5>
}

<br>
<div>
    @Html.ActionLink("Procesi", "ProcesINI")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}